name: Publish Packages
on:
  workflow_dispatch:
  release:
    types: [ created ]
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew build

      - name: Find JAR file
        id: find_jar
        run: echo "::set-output name=jar_path::$(find build/libs -name '*.jar' | head -n 1)"

      - name: Upload JAR to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.find_jar.outputs.jar_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

